version: "3.9"

services:
  shop-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram_shop_bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./database:/app/database
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; sys.exit(0)"]
      interval: 60s
      timeout: 10s
      retries: 3
